# Generated by Django 5.2.17 on 2026-08-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('total_waypoints', models.PositiveIntegerField(default=0, verbose_name='总航点数')),
                ('visited_waypoints', models.PositiveIntegerField(default=0, verbose_name='已巡检航点数')),
                ('coverage', models.FloatField(default=0.0, verbose_name='覆盖率')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_inspections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='stations.station')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InspectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '任务创建'), ('confirmed', '任务确认'), ('started', '任务开始'), ('paused', '任务暂停'), ('resumed', '任务恢复'), ('cancelled', '任务取消'), ('failed', '任务失败'), ('completed', '任务完成'), ('waypoint_visited', '航点已巡检'), ('waypoint_skipped', '航点已跳过'), ('media_uploaded', '素材已上传'), ('media_missing', '素材缺失')], max_length=20, verbose_name='事件类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inspections.inspectiontask')),
            ],
            options={
                'verbose_name': '巡检事件',
                'verbose_name_plural': '巡检事件',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(verbose_name='行')),
                ('column', models.PositiveSmallIntegerField(verbose_name='列')),
                ('order', models.PositiveIntegerField(verbose_name='序号')),
                ('status', models.CharField(choices=[('pending', '待巡检'), ('visited', '已巡检'), ('skipped', '已跳过'), ('failed', '失败')], default='pending', max_length=12, verbose_name='状态')),
                ('visited_at', models.DateTimeField(blank=True, null=True, verbose_name='巡检时间')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_waypoints', to='stations.panel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='inspections.inspectiontask')),
                ('uploaded_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoint_media', to='uploads.mediaasset')),
            ],
            options={
                'verbose_name': '航点',
                'verbose_name_plural': '航点',
                'ordering': ('task', 'order'),
                'constraints': [models.UniqueConstraint(fields=('task', 'panel'), name='uniq_waypoint_panel_per_task'), models.UniqueConstraint(fields=('task', 'order'), name='uniq_waypoint_order_per_task')],
            },
        ),
    ]
