# Generated by Django 5.2.17 on 2026-08-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='用户消息')),
                ('intent', models.CharField(blank=True, max_length=64, verbose_name='意图类型')),
                ('slots', models.JSONField(blank=True, default=dict, verbose_name='槽位参数')),
                ('response', models.TextField(blank=True, verbose_name='助手回复')),
                ('draft_action', models.JSONField(blank=True, default=dict, null=True, verbose_name='草稿动作')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('drafted', '已生成草稿'), ('confirmed', '已确认执行'), ('rejected', '已拒绝'), ('failed', '执行失败')], default='pending', max_length=16, verbose_name='状态')),
                ('source', models.CharField(choices=[('local', '本地规则引擎'), ('cloud', '云端 API')], default='local', max_length=16, verbose_name='来源')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '助手对话',
                'verbose_name_plural': '助手对话',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('query', '查询'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('export', '导出'), ('navigate', '导航跳转')], max_length=16, verbose_name='动作类型')),
                ('target', models.CharField(blank=True, max_length=64, verbose_name='目标对象')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '待执行')], default='pending', max_length=16, verbose_name='结果')),
                ('result_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='结果数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='assistant.agentconversation')),
            ],
            options={
                'verbose_name': '助手动作',
                'verbose_name_plural': '助手动作',
                'ordering': ('-created_at',),
            },
        ),
    ]
