# Generated by Django 5.2.17 on 2026-08-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0002_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cleaning', '需要清洗'), ('repair', '需要维修')], max_length=16, verbose_name='事件类型')),
                ('status', models.CharField(choices=[('open', '未处理'), ('closed', '已关闭')], default='open', max_length=16, verbose_name='状态')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='开启时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('reason', models.TextField(blank=True, verbose_name='异常原因')),
                ('closed_note', models.CharField(blank=True, max_length=240, verbose_name='关闭备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_events', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abnormal_events', to='stations.panel')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='recognition.recognitionjob')),
            ],
            options={
                'verbose_name': '异常事件',
                'verbose_name_plural': '异常事件',
                'ordering': ('-opened_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('panel', 'event_type', 'status'), name='uniq_open_event_per_panel_type')],
            },
        ),
    ]
