# Generated by Django 5.2.17 on 2026-08-06 09:27

import apps.uploads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_note', models.TextField(blank=True, verbose_name='区域备注')),
                ('status', models.CharField(choices=[('created', '已创建'), ('processing', '处理中'), ('completed', '已完成'), ('partial_failed', '部分失败')], default='created', max_length=20, verbose_name='批次状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='stations.station')),
            ],
            options={
                'verbose_name': '上传批次',
                'verbose_name_plural': '上传批次',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=12, verbose_name='素材类型')),
                ('original_file', models.FileField(max_length=500, upload_to=apps.uploads.models.media_upload_path, verbose_name='原始文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 类型')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('checksum', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('queued', '排队中'), ('processing', '识别中'), ('review', '待复核'), ('completed', '已完成'), ('failed', '失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='uploads.uploadbatch')),
            ],
            options={
                'verbose_name': '媒体素材',
                'verbose_name_plural': '媒体素材',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'video')), fields=('batch',), name='uniq_video_per_upload_batch')],
            },
        ),
    ]
