# Generated by Django 5.2.17 on 2026-08-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('version', models.CharField(max_length=40, unique=True, verbose_name='版本号')),
                ('model_type', models.CharField(choices=[('mock', '模拟模型'), ('yolo', 'YOLO')], max_length=16, verbose_name='模型类型')),
                ('model_path', models.CharField(blank=True, max_length=500, verbose_name='模型路径')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='指标')),
                ('class_config', models.JSONField(default=list, verbose_name='类别配置')),
                ('status', models.CharField(choices=[('candidate', '候选'), ('active', '启用'), ('retired', '已退役'), ('failed', '失败')], default='candidate', max_length=16, verbose_name='状态')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前启用')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_model_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_versions', to=settings.AUTH_USER_MODEL)),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_versions', to='datasets.datasetversion', verbose_name='数据集版本')),
            ],
            options={
                'verbose_name': '模型版本',
                'verbose_name_plural': '模型版本',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', '已创建'), ('queued', '已排队'), ('running', '训练中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='created', max_length=16, verbose_name='状态')),
                ('epochs', models.PositiveIntegerField(default=50, verbose_name='训练轮数')),
                ('image_size', models.PositiveIntegerField(default=640, verbose_name='图像尺寸')),
                ('batch_size', models.PositiveIntegerField(default=8, verbose_name='批大小')),
                ('device', models.CharField(default='mps', max_length=32, verbose_name='训练设备')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='指标')),
                ('log_file', models.CharField(blank=True, max_length=500, verbose_name='日志路径')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_training_runs', to='training.modelversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='datasets.datasetversion')),
                ('output_model_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_training_run', to='training.modelversion')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'ordering': ('-created_at',),
            },
        ),
    ]
