# Generated by Django 5.2.17 on 2026-08-06 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='结果序号')),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='左上 X')),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='左上 Y')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='宽度')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='高度')),
                ('original_class', models.CharField(choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修')], max_length=16, verbose_name='原始类别')),
                ('confirmed_class', models.CharField(blank=True, choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修')], max_length=16, verbose_name='确认类别')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='置信度')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='辅助原因')),
                ('review_status', models.CharField(choices=[('pending', '待复核'), ('confirmed', '已确认')], default='confirmed', max_length=16, verbose_name='复核状态')),
                ('is_demo_data', models.BooleanField(default=True, verbose_name='演示数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '检测结果',
                'verbose_name_plural': '检测结果',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='RecognitionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', '已创建'), ('queued', '已排队'), ('running', '运行中'), ('review', '待复核'), ('completed', '已完成'), ('failed', '失败')], default='created', max_length=16, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='进度')),
                ('adapter', models.CharField(default='mock', max_length=32, verbose_name='推理适配器')),
                ('is_demo_data', models.BooleanField(default=True, verbose_name='演示数据')),
                ('processed_frames', models.PositiveIntegerField(default=0, verbose_name='已处理帧数')),
                ('total_frames', models.PositiveIntegerField(default=1, verbose_name='总帧数')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '识别作业',
                'verbose_name_plural': '识别作业',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_class', models.CharField(choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修')], max_length=16, verbose_name='修改前类别')),
                ('confirmed_class', models.CharField(choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修')], max_length=16, verbose_name='确认类别')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='复核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
