# Generated by Django 5.2.17 on 2026-08-06 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionjob',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_job', to='uploads.mediaasset'),
        ),
        migrations.AddField(
            model_name='detection',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='recognition.recognitionjob'),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='recognition.detection'),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detection_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='uniq_detection_sequence'),
        ),
    ]
