# Generated by Django 5.2.17 on 2026-08-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionjob',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recognition_jobs', to='training.modelversion', verbose_name='模型版本'),
        ),
    ]
