# Generated by Django 4.2.30 on 2026-08-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('web', '网页报告'), ('excel', 'Excel 报告'), ('pdf', 'PDF 报告')], max_length=10, verbose_name='报告类型')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('ready', '已就绪'), ('failed', '失败')], default='generating', max_length=10, verbose_name='状态')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('snapshot_data', models.JSONField(blank=True, default=dict, verbose_name='快照数据')),
                ('file', models.FileField(blank=True, max_length=500, upload_to='reports/', verbose_name='导出文件')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('progress', models.IntegerField(default=0, verbose_name='生成进度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'ordering': ('-created_at',),
            },
        ),
    ]
