# Generated by Django 5.2.17 on 2026-08-06 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='区域名称')),
                ('direction', models.CharField(choices=[('east', '东区'), ('south', '南区'), ('west', '西区'), ('north', '北区')], max_length=12, verbose_name='方向')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='电站代码')),
                ('name', models.CharField(max_length=120, verbose_name='电站名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '电站',
                'verbose_name_plural': '电站',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SolarArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='阵列编号')),
                ('rows', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='行数')),
                ('columns', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='列数')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrays', to='stations.region')),
            ],
            options={
                'verbose_name': '光伏阵列',
                'verbose_name_plural': '光伏阵列',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_code', models.CharField(max_length=40, verbose_name='完整编号')),
                ('short_code', models.CharField(max_length=24, verbose_name='短编号')),
                ('row', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='行')),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='列')),
                ('current_status', models.CharField(choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修'), ('processing', '识别中'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='当前状态')),
                ('last_recognized_at', models.DateTimeField(blank=True, null=True, verbose_name='最近识别时间')),
                ('array', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='stations.solararray')),
            ],
            options={
                'verbose_name': '光伏组件',
                'verbose_name_plural': '光伏组件',
                'ordering': ('array_id', 'row', 'column'),
            },
        ),
        migrations.AddField(
            model_name='region',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='stations.station'),
        ),
        migrations.CreateModel(
            name='PanelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', '正常'), ('cleaning', '需要清洗'), ('repair', '需要维修'), ('processing', '识别中'), ('unknown', '未知')], max_length=16, verbose_name='状态')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='原因')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('source', models.CharField(default='demo_seed', max_length=32, verbose_name='来源')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='stations.panel')),
            ],
            options={
                'verbose_name': '组件状态历史',
                'verbose_name_plural': '组件状态历史',
                'ordering': ('-recorded_at',),
                'constraints': [models.UniqueConstraint(fields=('panel', 'recorded_at'), name='uniq_panel_history_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='solararray',
            constraint=models.UniqueConstraint(fields=('region', 'code'), name='uniq_array_code_per_region'),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('array', 'row', 'column'), name='uniq_panel_position_per_array'),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('array', 'full_code'), name='uniq_panel_code_per_array'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='uniq_region_name_per_station'),
        ),
    ]
